### ISSUE TITLE
How to escape SQL functions so they are not treated as strings in DB?

### ISSUE THREAD

**Issue by vincenthawke** [sidorares/node-mysql2#1000]
I am trying to do an insert where I want to run a SQL function like `NOW()` to populate a `DATE` field. I pass it as a string and I believe it inserts it as a string as well which results in date not being properly inserted (all zeros). How do we properly specify SQL functions that we want to run using this library? 

```
connection.execute(
   "INSERT INTO daily (date) VALUES (?)",
   ["NOW()"], (err, results, fields) => { });
```

I am currently solving this by creating a date as string inside node but it would be awesome if I could use sql functions.

**Comment by sidorares** [comment]
with `.execute()` parameters you pass into a statement must exactly match to what PS expect. If you want your query to be executed like `INSERT INTO daily (date) VALUES (NOW())` server side you must prepare+execute it like this because statement itself has no parameters:

```js
connection.execute( "INSERT INTO daily (date) VALUES ( NOW())");
```

The only other option if you want to keep `INSERT INTO daily (date) VALUES (?)` as your query is to pass date from client:  connection.execute( "INSERT INTO daily (date) VALUES (?)", [Date.now()]);

The whole point of "execute" / prepared statements is to separate code from data. Code is your sql and data are parameters, and they are sent to server in separate packets ( subsequent `.execute()` invocations don't send query at all, just prepared statement id + params ). 

for client-side sql parameters interpolation ( `.query(sql, params )` )  both this driver and mysqljs/mysql are using https://www.npmjs.com/package/sqlstring module. Here is an example from readme:

```js
var CURRENT_TIMESTAMP = { toSqlString: function() { return 'CURRENT_TIMESTAMP()'; } };
var sql = SqlString.format('UPDATE posts SET modified = ? WHERE id = ?', [CURRENT_TIMESTAMP, 42]);
console.log(sql); // UPDATE posts SET modified = CURRENT_TIMESTAMP() WHERE id = 42
```
