### ISSUE TITLE
affectedRows is 1 when `ON DUPLICATE KEY UPDATE` sets the same value as current

### ISSUE THREAD

**Issue by worudso** [sidorares/node-mysql2#1097]
> environment
> mysql2: 2.1.0
> mysql server: 8.0.18

AFAIK `affectedRows` gives 0 when the rows with given key already exists and the update query makes no changes to its value.
MySQL workbench shows the expected value on its console while node-mysql2 doesn't.

Here is a simple example. 
This is the create statement.
```sql
CREATE TABLE `new_table` (
  `id` int(11) NOT NULL,
  `x` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
And this is the query.
```sql
INSERT INTO new_schema.new_table SET id = 1, x = "hi" ON DUPLICATE KEY UPDATE x = "hi"
```
When you tried this command twice, then at the second execution you'll see `0 rows(s) affected` on workbench.
```typescript
import { createPool } from "mysql2/promise";

(async () => {
  const pool = await createPool("connection string")
  const connection = await pool.getConnection();
  console.log(await connection.query(`INSERT INTO new_schema.new_table SET id = 1, x = "hi" ON DUPLICATE KEY UPDATE x = "hi"`));
})()
```
But I see `affectedRows: 1` in console with this code.

**Comment by sidorares** [comment]
the difference might be because of different [CLIENT_FOUND_ROWS](https://dev.mysql.com/doc/refman/5.7/en/mysql-affected-rows.html) flag used by workbench:

>  For UPDATE statements, the affected-rows value by default is the number of rows actually changed. If you specify the CLIENT_FOUND_ROWS flag to mysql_real_connect() when connecting to mysqld, the affected-rows value is the number of rows “found”; that is, matched by the WHERE clause.

This flag is [on by default](https://github.com/sidorares/node-mysql2/blob/f9b9f96c2cf1dace5570d60a89caacec2ecb4b48/lib/connection_config.js#L188) in mysql2 and mysqljs/mysql drivers 

see https://github.com/sidorares/node-mysql2/issues/875#issuecomment-440866842 for previous discussion
