### ISSUE TITLE
Seems like escaping query identifiers in prepare stmts do not work

### ISSUE THREAD

**Issue by Sfinx** [sidorares/node-mysql2#1190]
Having dynamic table names so prepared cache can be huge. Trying to use something like "select * from ??" as in original node-mysql but it do not works with node-mysql2. Any solutions ?

**Comment by Sfinx** [comment]
Solved LOCK with DLM, so escaping indentifiers question remains

**Comment by sidorares** [comment]
You might be able to set max size of PS cache (need to double check), but in general if you can't change you DB design and feel that the only solution is to use dynamic query generation it's better not to use prepared statements at all ( just use `conn.query()` instead of `conn.execute()` for that particular dynamic part )

**Comment by Sfinx** [comment]
I see, ok - sounds like solution, thanks ! But it still not clear why the '??' is not supported..

**Comment by sidorares** [comment]
> But it still not clear why the '??' is not supported..

general idea is that PS are meant to separate "code" and "data" ( SQL from parameters ).
More specifically - this driver only supports features that mysql server support. If syntax does not work with mysq cli and `PREPARE ...` it won't work here as well. See more documentation at https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html#idm45306656656752
