### ISSUE TITLE
Could insert using .query() may still in progress in mysql2/promise after the promise is resolved?

### ISSUE THREAD

**Issue by haposan06** [sidorares/node-mysql2#1299]
Hi, 
I have series of queries that need to be executed in order. There's alot of insert queries which needs data to be inserted first in the previous order. 

```
await Promise.mapSeries(queries, async(q)=>{
      const queryNameClient = `${q.queryName} - ${this.clientId}`;
      console.log(`Start running queries Query Order: ${q.queryOrder} -  ${queryNameClient}`);
      console.time(`${queryNameClient} query finished in`);
      const rawDatas = await dbConnectionPool.query(q.queryStr);
      data = rawDatas[0];
      console.timeEnd(`${queryNameClient} query finished in`);
      console.log(`The result for ${queryNameClient} query is: ${JSON.stringify(rawDatas)}`);
    })
```

The thing is, there's probability that the Insert in later order will give 0 row result because it needs to fetch from the table that will be populated by the Insert query in the previous order. 

How can I fix this? Will changing to .execute() may solve the problem?

**Comment by sidorares** [comment]
sorry somehow missed the question back then. The commands in a single connection are always sequential, but since you using a pool in theory all your commands might start at the same time and run in parallel ( same for .execute() ). You need to add this to your logic somehow, if result of one query depends on another don't run it in parallel, await for the results and start dependant query when you have the data
