### ISSUE TITLE
How i can get the output as json object without having the other unncessary object 

### ISSUE THREAD

**Issue by Amrkamel1** [sidorares/node-mysql2#1308]
Is there an option to return the query output as a JSON object, the first array  in the screenshot is what I'm expecting but then I'm getting a punch of other unnecessary objects is there an option to disable that 

![image](https://user-images.githubusercontent.com/32042806/112466745-77bd3000-8d66-11eb-96c5-4446a3c19f3e.png)

**Comment by sidorares** [comment]
Just ignore them if you don't need column definitions. both `.query()` and `.execute()` return `[rows, fields]` ( promise api ) or call callback with `callback(null, rows, fields)` with successful select-like query where rows is an array of result rows and fields is an array of column definition that each row follow. You can force client to skip conversion to a field name keyed object and instead emit each rows as subarray of columns using [rowsAsArray](https://github.com/sidorares/node-mysql2#array-results) option

what can probably improved here - custom inspect hook so that column definition is displayed in a nicer way when you console.log it

**Comment by Amrkamel1** [comment]
@sidorares that's cool thanks, man.
However, it would be good to have an option to hide these arrays of column definitions, when using MariaDB js I just get one JSON object with the required info.
