### ISSUE TITLE
mysql error with cronjob (node-cron)

### ISSUE THREAD

**Issue by segun-flexible** [sidorares/node-mysql2#1348]
Am using node-cron to run a cron job every 12 Oclock Midnight, the job am running is to increment some data on the user table,
the issue now is that the job will run twice.

e.g I wanna increment 15 to 16 after 12 o'clock, it will turn to 17 instead of 16.

have tried my possible best to detect the issue, am unable.

**Comment by codinggirl** [comment]
This is not ralated with `mysql2` module.

According to your situation, I think the problem may be:

- Your node.js application runs on a cluster mode. For example, you use pm2 to manage the lifecycle of your application, and use its cluster feature.
- Your node.js application runs on 2 instances. This happens when your run the scripts twice. Your should use the linux command `ps aux | grep node` to see the running process(es).

May this information would help you.

**Comment by segun-flexible** [comment]
Thanks 🙏
