### ISSUE TITLE
Selected double value gets rounded

### ISSUE THREAD

**Issue by shawnam** [sidorares/node-mysql2#153]
I noticed this in my application, so I created a small contrived example to demonstrate the problem.

```
create table test (c double unsigned);
insert into test set c=0.27890624999999997;
```

From within my terminal:
```
mysql> select c FROM test;
+---------------------+
| c                   |
+---------------------+
| 0.27890624999999997 |
+---------------------+
1 row in set (0.00 sec)
```
So all good.

Using mysql2:

```
var connection = mysql.createConnection({
    host     : <host>,
    user     : <user>,
    password : <pw>,
    database : <db>
});
connection.query("SELECT c FROM test", function (err, rows) {
    console.log(rows);
});
connection.end();
```

On the console I get:
```
[ { c: 0.27890625 } ]
```

I think this is somehow related to parseFloat in packets.js, but I've not pinpointed exactly what's going on quite yet. FWIW, I'm not seeing the rounding in the https://github.com/felixge/node-mysql package. Is this behavior expected for some reason that I'm missing?

**Comment by sidorares** [comment]
some background: in text protocol ( non-prepared statements ) everything is sent as text, so we get 19 bytes of "0.27890624999999997" over wire. parseFloat is an optimisation as it turns out that string creation in V8 is quite expensive ( compared to Buffer byte access ) so simple `parseFloat(packet.readString()` is much slower than `packet.parseFloat(19)` because first creates intermediate string and discards it immediately.

The problem your example shows is following:

(code to reproduce without making connection)

```js
var Packet = require('./lib/packets/packet.js');
var a = '0.27890624999999997';
var p = new Packet(0, new Buffer(a));
var f = p.parseFloat(a.length);
console.log(f);
```

parseFloat reads all numbers one by one and interprets them as integer, and keeps track of exponent and dot position. At very end it returns `return result/factor` which is 27890625000000000 and 100000000000000000. The problem here is due to the way doubles are stored 27890624999999990 + 9 is 27890625000000000.

**Comment by sidorares** [comment]
I'd recommend not to compare floating point for equality anyway and use decimalnumber on mysql side / convert manually to BigNumber client side if you need arbitrary precision arithmetics.

**Comment by sidorares** [comment]
If you want the result to be identical to original 8byte IEEE double without to/from string precision loss you can use binary protocol (`execute` instead of `query`):

```js
var connection = require('./test/common.js').createConnection();
connection.query("create temporary table dtest (c double unsigned)");
connection.query("insert into dtest set c=0.27890624999999997");
connection.query("SELECT c FROM dtest", function (err, rows, cols) {
    console.log(rows[0].c);
});
connection.execute("SELECT c FROM dtest", function (err, rows, cols) {
    console.log(rows[0].c);
    connection.end();
});
```

outputs

```
0.27890625
0.27890624999999997
```

**Comment by sidorares** [comment]
note that it's known JS problem:
```
> console.log(0.27890624999999999)
0.27890624999999997
```
