### ISSUE TITLE
HOW TO RETURN mysql.RowDataPacket result 

### ISSUE THREAD

**Issue by jriffs** [sidorares/node-mysql2#1593]
i am trying to get results from a select statement 
here's my code
```
const connection = mysql.createConnection(db_URL)

connection.connect((err) => {
    if (err) {
        throw err
    }
    console.log('successfully connected 👍👍')
})

function getAll(table) {
    let result 
    const query_string = 'SELECT * FROM ${table}'
    connection.query(query_string, (err, rows) => {
        if (err) throw err
        result = rows
    })
    return result
}
```
but when i try to log out the result, it gives undefined
`console.log(getAll('Projects')) //undefined`

**Comment by sidorares** [comment]
@jriffs I suggest to start with "how to deal with asynchronous control flow in javascript" tutorials. Example articles:

https://eloquentjavascript.net/11_async.html
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing

Re your question: you the results from the database are coming later than your `return result` statement, and because of that you can't see the effect of `result = rows` assignment. One way of solving that is to move the code that need rows to when rows are received:

```js

function getAll(table, onRowsReceived) {
    let result 
    const query_string = 'SELECT * FROM ${table}'
    connection.query(query_string, (err, rows) => {
        if (err) {
           return onRowsReceived(err);
        }
        onRowsReceived(null, rows); 
    })
}

getAll('Projects', (err, rows) => {
   if (err) {
       console.log('error getting projects');
   } else {
      console.log(rows);
   }
})
```

With async/await the order of flow _might_ look slightly more natural but I suggest to get some confidence in callback style control passing first

**Comment by jriffs** [comment]
@sidorares JavaScript has once again given me a slap on the face 😅😂 ... i actually know how to handle async flow .. infact the the function was  first async/await .. my brain is absolute mush right now😅, haven't closed my eyes in 2 days. but thank you for the explanation💪

**Comment by jriffs** [comment]
okay i don't know what's up but it seems like i don't even understand javascript anymore 😂 .. i just tried your solution, and it's still the same 🤷‍♂️🤷‍♂️
