### ISSUE TITLE
Confusion about transaction code:

### ISSUE THREAD

**Issue by smhk** [sidorares/node-mysql2#1618]
My transaction code:

```js
try {
    const cn = await pool.getConnection()
    await cn.beginTransaction()

    await cn.execute(' ...
    await cn.execute(' ...

    await cn.commit()
}
catch {
    await cn.rollback()
}
```

But am I wrong? Should it be:

```js
const cn = await pool.getConnection()
try {
    await cn.beginTransaction()

    await cn.execute(' ...
    await cn.execute(' ...

    await cn.commit()
}
catch {
    await cn.rollback()
}
```

But wait! Should it be?

```js
const cn = await pool.getConnection()
await cn.beginTransaction()
try {
    await cn.execute(' ...
    await cn.execute(' ...

    await cn.commit()
}
catch {
    await cn.rollback()
}
```

I'm afraid I don't know the answer. Thanks in advance anyone who can advise. (It may help others also?)

**Comment by sidorares** [comment]
beginTransaction / commit / rollback are just [simple helpers](https://github.com/sidorares/node-mysql2/blob/6d3460946da9bd8ced862c355f8d4bb06f87e0b5/lib/connection.js#L704-L714) to perform `START TRANSACTION` / `COMMIT` / `ROLLBACK` queries

To me 3rd example is the most correct but I'm not an SQL / mysql export

Possible reasons why `pool.getConnection()` can fail: network error in the process of getting a new connection, too many connections limit reached (server side), client side limit on number of open connections

Not sure when `START TRANSACTION` can fail ( reasons other than connection is killed because of network error or other client `KILL thread_id` ) but I guess rollback only makes sense after successful `START TRANSACTION`

**Comment by sidorares** [comment]
there was a discussion somewhere here about possible better helper api that would handle this pattern, for example something similar to https://github.com/porsager/postgres#transactions ( I've started some initial work [here](https://github.com/sidorares/node-mysql2/pull/1539) )

**Comment by maoweifan** [comment]
I think the first one is wrong, because cn is in try, catch can't get the reference

<img width="443" alt="image" src="https://user-images.githubusercontent.com/51221758/187757456-5f836050-0daf-450b-8e72-4809316d1be2.png">
And in the experience of some other languages (such as java), the opening of the transaction will also be put outside the try, because the failure of the transaction to open does not actually need to be rolled back, only if there is an error during the execution process, it will be rolled back. capture

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/51221758/187759234-db445f60-6128-444b-99d6-ccaa0cf581a3.png">

**Comment by smhk** [comment]
thanks for the fantastic info @sidorares .  I'm sure this will be helpful to others also.  Additionally it's one of those cases where on the internet, there is some bad/incorrect example code, which gets repeatedly copied. Thanks again, mysql2 is totally incredible

(Just FYI there was a delay with ghub notifying these comments, thanks again.)

**Comment by trasherdk** [comment]
Isn't the point of transactions, to isolate a group of query/execute commands?

If, for some reason, `beginTransaction()` fail, the following group of commands should never run.

Some back-off/retry on `beginTransaction()` could be useful :)

**Comment by sidorares** [comment]
@trasherdk in the example above if beginTransaction fails the control goes to catch block

**Comment by trasherdk** [comment]
@sidorares If by example above, you mean:
```js
const cn = await pool.getConnection()
try {
    await cn.beginTransaction()

    await cn.execute(' ...
    await cn.execute(' ...

    await cn.commit()
}
catch {
    await cn.rollback()
}
```
Then I'd expect you to be right.
But with `beginTransaction()` outside the `try {} catch {}` block, how would control go to `catch {}`?

**Comment by sidorares** [comment]
Yes, currently you are expected to handle this manually. There is definitely a room for improvement, feel free to suggest your api

**Comment by trasherdk** [comment]
Well, the snippet I quoted, is how I would expect the flow to go.

I'd probable throw in a few [SELECT ... LOCK IN SHARE MODE](https://dev.mysql.com/doc/refman/5.6/en/select.html) and [SELECT ... FOR UPDATE](https://dev.mysql.com/doc/refman/5.6/en/select.html) before any `execute()` :)

**Comment by sidorares** [comment]
we could have a helper like this as a replacement for beginTransaction / commit / rollback:

```js
const result = await connection.transaction(async connection => {
   connection.execute(/*...*/);
   return connection.query(/*...*/);
}) 

// also pool - a shortcut for pool.getConnection + connection.transaction
await pool.transaction(async connection => {
   connection.execute(/*...*/);
   connection.query(/*...*/);
}) 
```

wdyt @trasherdk ?

**Comment by trasherdk** [comment]
If `pool.transaction( conn => {})` includes some kind of retry, then cool.
Otherwise, it's better handled by whatever flow it's part of.

```js
// also pool - a shortcut for pool.getConnection + connection.transaction
await pool.transaction(async connection => {
   await connection.execute(/*...*/);
   const [ cols, rows ] = await connection.query(/*...*/);
})
```
But how is `commit`/`rollback` handled in this construction?
```js
// also pool - a shortcut for pool.getConnection + connection.transaction
await pool.transaction(async connection => {
   await connection.execute(/*...*/);
   const [ cols, rows ] = await connection.query(/*...*/);

  connection.commit()
}).catch(error) {
  connection.rollback()
}
```
It might be better to bake the `retry`/`back-off` into the existing `beginTransaction()`

`conn.beginTransaction(retry=5, retryTime=500, backoff=100)`
or
`conn.beginTransaction({ retry: 5, retryTime: 500, backoff: 100 })`
