### ISSUE TITLE
Execute the built-in function 'from_base64' to return Buffer?

### ISSUE THREAD

**Issue by JQiue** [sidorares/node-mysql2#1635]
I hope to get

```js
const data = await exec(`SELECT from_base64('aGVsbG8sIHdvcmxk') as content`);
console.log(data);  // [ { content:  'hello, world' } ]
```

in fact

```js
const data = await exec(`SELECT from_base64('aGVsbG8sIHdvcmxk') as content`);
console.log(data);  // [ { content: <Buffer 68 65 6c 6c 6f 2c 20 77 6f 72 6c 64> } ]
````

**Comment by JQiue** [comment]
I need to process the data again?

**Comment by sidorares** [comment]
the Buffer you are getting contains base64 decoded `aGVsbG8sIHdvcmxk` data which is 'hello, world' string, just use `data[0][0].content.toString()` on result

The reason its returned as Buffer is because result of the `from_base64` reports its charset as code 63 - BINARY, when this happens mysql reads data as a buffer and its up to you how to interpret it ( convert to latin1 or utf8 string or do something else with the data )

https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/parsers/text_parser.js#L66

https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/parsers/binary_parser.js#L75

**Comment by JQiue** [comment]
Useful help, I close this issue
