### ISSUE TITLE
BigInt is truncated in results

### ISSUE THREAD

**Issue by Gami13** [sidorares/node-mysql2#1640]
When using: 
```
let query = "SELECT userId, id, isUsed FROM verifyaccount WHERE hash = ?";
let [results, fields] = await db.execute(query, [hash]);
```

both id and userId show wrong values.

The values are userId: 97073043121143000, id: 97073043133733650, when they should be userId: 97073043121143016 id: 97073043133733649.

Correct values are returned when querying directly to the database, database column is set to BigInt

**Comment by sidorares** [comment]
Do you have `supportBigNumbers` flag enabled? 

See [connection options](https://github.com/mysqljs/mysql#connection-options):

> supportBigNumbers: When dealing with big numbers (BIGINT and DECIMAL columns) in the database, you should enable this option (Default: false).
bigNumberStrings: Enabling both supportBigNumbers and bigNumberStrings forces big numbers (BIGINT and DECIMAL columns) to be always returned as JavaScript String objects (Default: false). Enabling supportBigNumbers but leaving bigNumberStrings disabled will return big numbers as String objects only when they cannot be accurately represented with [JavaScript Number objects] (https://tc39.es/ecma262/#sec-ecmascript-language-types-number-type) (which happens when they exceed the [-2^53, +2^53] range), otherwise they will be returned as Number objects. This option is ignored if supportBigNumbers is disabled.

Relevant code: https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/parsers/binary_parser.js#L60-L71

**Comment by Gami13** [comment]
> Do you have `supportBigNumbers` flag enabled? 
> 
> See [connection options](https://github.com/mysqljs/mysql#connection-options):
> 
> > supportBigNumbers: When dealing with big numbers (BIGINT and DECIMAL columns) in the database, you should enable this option (Default: false).
> bigNumberStrings: Enabling both supportBigNumbers and bigNumberStrings forces big numbers (BIGINT and DECIMAL columns) to be always returned as JavaScript String objects (Default: false). Enabling supportBigNumbers but leaving bigNumberStrings disabled will return big numbers as String objects only when they cannot be accurately represented with [JavaScript Number objects] (https://tc39.es/ecma262/#sec-ecmascript-language-types-number-type) (which happens when they exceed the [-2^53, +2^53] range), otherwise they will be returned as Number objects. This option is ignored if supportBigNumbers is disabled.
> 
> Relevant code: https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/parsers/binary_parser.js#L60-L71

This fixed it, thanks for the help, and sorry for not finding it myself
