### ISSUE TITLE
Typescript issue with result of a promised query

### ISSUE THREAD

**Issue by ChezCoder** [sidorares/node-mysql2#1654]
<img width="670" alt="Screen Shot 2022-10-19 at 00 47 27" src="https://user-images.githubusercontent.com/62308406/196600042-ce4679c4-ff1d-43c0-8763-0b2ee563b638.png">

<img width="748" alt="Screen Shot 2022-10-19 at 00 47 54" src="https://user-images.githubusercontent.com/62308406/196600102-5e98d514-85d6-4081-8f66-d403385e9c3f.png">

**Is there a way to fix this issue dynamically? Or am I forced to cast `rows` to `any[]` type?**

**Comment by sidorares** [comment]
can you paste example code I can `tsc` locally reproduce compiler error?
`.length` should be covered by one of the array options in the returned type

**Comment by DaveLo** [comment]
Without code it's hard to say what your issue is, but you can type narrow your rows, query and execute are generics 

### example
```typescript
const [result] = connection.query<RowDataPacket[]>("SELECT 1 + 1")
```
if you know the shape of your results you can also extend RowDataPacket a couple of ways
```typescript
interface QueryResult extends RowDataPacket { count: number }
// or
interface ICount { count: number }
type QueryResult = ICount & RowDataPacket;

const [result] = connection.query<QueryResult[]>("SELECT 1 + 1 AS count");
```

OkPacket(`[]`) is what is returned from an insert or update action (or batch).

**Comment by ChezCoder** [comment]
Oh I didn't realize there is a type parameter! Thanks, that's really helpful.

Could this be better documented so it isn't as confusing?

**Comment by ChezCoder** [comment]
@sidorares I think your problem is `OkPacket` and `ResultSetHeader` aren't arrays, so `.length` isn't covered by the type union.

<img width="715" alt="Screen Shot 2022-10-19 at 09 32 56" src="https://user-images.githubusercontent.com/62308406/196705826-0863f66c-657b-4754-82b7-fe36ad633096.png">

**Comment by sidorares** [comment]
> problem is OkPacket and ResultSetHeader aren't arrays

but `OkPacket[]` ( and few others ) are, and this is a union? I'm not a heavy typescript user so maybe others can help. Example code would be helpful as well

**Comment by ChezCoder** [comment]
> > problem is OkPacket and ResultSetHeader aren't arrays
> 
> but `OkPacket[]` ( and few others ) are, and this is a union? I'm not a heavy typescript user so maybe others can help. Example code would be helpful as well

Nope, you need to remove `OkPacket` from the union and keep `OkPacket[]`.

Also either remove `ResultSetHeader` or just change it to `ResultSetHeader[]`.

Doesn't seem like OkPacket has a `.length` property
<img width="240" alt="Screen Shot 2022-10-20 at 08 04 12" src="https://user-images.githubusercontent.com/62308406/196943449-3e652884-a138-4d8f-a7c7-d47deb573dbd.png">

Nor does ResultSetHeader
<img width="281" alt="Screen Shot 2022-10-20 at 08 04 22" src="https://user-images.githubusercontent.com/62308406/196943480-2c64b482-dde5-4646-ad81-a439b2605b1e.png">
<hr>
You could also just change the type parameter to default as `any[]`.
<img width="126" alt="Screen Shot 2022-10-20 at 08 05 07" src="https://user-images.githubusercontent.com/62308406/196943639-977a18eb-bda0-43e1-9128-d74d85b4ff7b.png">
<img width="859" alt="a" src="https://user-images.githubusercontent.com/62308406/196944426-715a652f-9ae0-4154-a84b-415054001434.png">

> Example code would be helpful as well

Database.ts
```ts
import mysql2, { Pool, RowDataPacket } from "mysql2/promise";

export namespace Database {
    const pool = mysql2.createPool({
        "host": config.mysql.host,
        "user": config.mysql.user,
        "password": config.mysql.pass,
        "database": config.mysql.database,
        "waitForConnections": true,
        "connectionLimit": 10
    });

    export function getPool(): Pool {
        return pool;
    }
}
```

index.ts ** BEFORE MY FIX **
<img width="696" alt="Screen Shot 2022-10-20 at 08 12 53" src="https://user-images.githubusercontent.com/62308406/196945241-a91187d3-31ce-4578-9f4e-8e797747931e.png">
ERROR:
<img width="763" alt="Screen Shot 2022-10-20 at 08 13 04" src="https://user-images.githubusercontent.com/62308406/196945270-d6305110-fefe-4e52-8145-7bf5b9fb9a78.png">

index.ts ** AFTER MY FIX **
<img width="694" alt="Screen Shot 2022-10-20 at 08 11 31" src="https://user-images.githubusercontent.com/62308406/196944990-c7af326a-42e6-41ee-9cc4-0a3d478352b1.png">
NO ERROR

**Comment by ChezCoder** [comment]
> but `OkPacket[]` ( and few others ) are, and this is a union?

Keep in mind that a union type is a combination of all the types.

So TypeScript will find the **common properties and methods** among the types.

```ts
type foo = number | number[]

const bar: foo = 1; // This works

// But TypeScript does not cast bar to Number
// TypeOf bar is still foo which in turn is still Number | Number[]

bar.length; // This doesn't work, because .length is not a common property among Number and Number[]
```

<img width="820" alt="Screen Shot 2022-10-20 at 08 19 45" src="https://user-images.githubusercontent.com/62308406/196946746-c1a873a4-a305-413b-8636-0334844ee973.png">

**Comment by ChezCoder** [comment]
Created a pull request at #1655

**Comment by sidorares** [comment]
@ChezCoder current `.query()` API and typings reflect what is returned over low level wire protocol for COM_QUERY command: depending on your query ( insert/modify/delete; select; multiple queries result (that can be mix of insert/modify/delete/select ), and as a result we have this union type and you can expect all the possible combinations of Ok / Rows[] ( for insert / select ) or Array[ Ok | Rows[] ] ( multiple selects )

![image(1)](https://user-images.githubusercontent.com/173025/197073020-299ecd59-bce6-4dbd-a111-e8ea6894a8e9.svg)

If you know you expect single ok or rows response you can parametrise `.query()` call, or alternatively you look dynamically at what is returned and only access array properties when you get instance of an array. In the below example typescript knows you can access `bar.length` because of  `if (Array.isArray(bar))` check

```js
type foo = number | number[];

function fooReturn() {
    const d = +new Date();
    if (d%2) {
        return 1;
    } else {
        return [1, 2, 3];
    }
}

const bar = fooReturn();

if (Array.isArray(bar)) {
  console.log(bar.length);
}
```

**Comment by DaveLo** [comment]
Tacking on to the great explanation from @sidorares , 

The reason that query and execute are both generics is so that you can tell typescript what result you are expecting. The type narrowing described above isn't necessary if you use the built in functionality.

### Your example

```typescript
(
  async function () {
    const [ rows ] = await Database.getPool().query<RowDataPacket[]>("SELECT * FROM `ExampleTable`");
    console.log(rows.length)
  }
)()
```

Your PR adding a default any[] is a strictly worse solution than just using the types as written.  I do think it could be better documented though.

I know the datapacket types were originally brought in from @types/mysql when types were brought into the repository and they map to the actual low level constructs, but it might be useful to have a utility generic that does the thing I suggested above.

### generic row?
```typescript
type TypedRowDataPacket< Row = Record< string, unknown > > = T & RowDataPacket;

interface User {
  id: string;
  name: string;
}
type UserRow = TypedRowDataPacket< User >

const [ rows ] = await db.execute< Pick< UserRow, "name" >[] >("select name from `Users` WHERE id = ?", [id]);

if (rows.length === 0) { 
  throw new Error( "No users found" )
}

console.log( rows[ 0 ] );
```

**Comment by ChezCoder** [comment]
Ok, after reading your answer, I guess it sort of makes sense.

But I would appreciate it if this was better documented.

**Comment by sidorares** [comment]
> But I would appreciate it if this was better documented.

Agreed, we can improve on that

**Comment by FrancescoBorzi** [comment]
> > But I would appreciate it if this was better documented.
> 
> Agreed, we can improve on that

is there any news about this?
