### ISSUE TITLE
Query.stream exception

### ISSUE THREAD

**Issue by asafyish** [sidorares/node-mysql2#174]
Hi,

I am getting this exception:
.../mysql2/lib/commands/query.js:221
    if (!stream.push(row)) self._connection.pause();
                                           ^
TypeError: Cannot read property 'pause' of undefined

If I put a breakpoint there, I can see that indeed _connection is null.
The fix was to add:
```js
this._connection = connection;
```
in Query start method (Query.js line 32)

**Comment by danieljuhl** [comment]
I just encountered this issue if using a prepared statement combined with streaming.

If I fetch eg. 50 rows, no problems, if I fetch eg. 75 rows, I get
```
node_modules/mysql2/lib/commands/query.js:256
      self._connection.pause();
                      ^
TypeError: Cannot read property 'pause' of undefined
```

I tried to modify the file, and log what `self` and `self._connection is` - and connection is always undefined, and it looks like the problem is, that a `self` is not a `Query` but an `Execute`, which don't hold the `_connection.`
