### ISSUE TITLE
.execute with parameterized order by

### ISSUE THREAD

**Issue by fabiokounang** [sidorares/node-mysql2#1927]
Hello, i am having an issue. So currently in production everything seems goes well, but suddenly I got "max_prepared_stmt_count" error. All my query already parameterized (Create, Update, Delete, and Read) but orderby and pagination. So is it the problem ? should I paramterized the order by and limit query too ? Because I have tried but it occurs an error. Please help. thank you @sidorares :D

Below is all my query example
```
return database.execute(`SELECT id, username, password, role, status FROM admin WHERE username = ?`, [username]);
return database.execute(`SELECT id, username, role, status FROM admin WHERE id = ?`, [id]);
return database.execute(`UPDATE admin SET username = ?, role = ?, status = ? WHERE id = ?`, [admin.username, admin.role, admin.status, admin.id]);
return database.execute(`UPDATE admin SET password = ? WHERE id = ?`, [admin.password, admin.id]);
return database.execute(`DELETE FROM admin WHERE id = ?`, [id]);
```

**Comment by elimelt** [comment]
Look into using ```database.unprepare(queryString)```.

See documentation below:
https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md



If this doesn't fix your problem, keep on reading.

Can you provide the queries that resulted in errors? Depending on how you are implementing pagination, there might be something going on due to MySQL's automatic reparsing of prepared statements when there was a change detected in the metadata of a query (say for instance a cursor).

If you can access the performance_schema DB in your instance of MySQL server, you can take a look at what is being stored, allowing you to confirm that you aren't re-storing any queries due to client side parametrization. 

To see the SQL being stored:
```select SQL_TEXT from performance_schema.prepared_statements_instances;```
Or, to see the count of prepared statements:
```select count(*) from performance_schema.prepared_statements_instances;```

To deallocate manually with SQL, take a look at the DEALLOCATE/DROP command. More on this [here](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-prepared-statements-instances-table.html)

Prepared Statement caching should only persist during a given session, so depending on how you're using your DB in production vs. development/testing, this might be the cause of varying behavior between your different enviornments.

**Comment by sidorares** [comment]
In addition to @elimelt answer:

statements are automatically unprepared ( in a least recently used order ) once number of prepared statements in a single connection reaches `maxPreparedStatements` config value for that connection ( default value is [16000](https://github.com/sidorares/node-mysql2/blob/209793e31d6ea4083aa9c0d917ea951a8b608b01/lib/connection_config.js#L180)), however on a server side e [max_prepared_stmt_count](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_prepared_stmt_count) is a limit for total number of statements from all incoming connections. Prepared statements are scoped per connections, two connections preparing 2 identical statements `select ? as result` create 2 statements on the server

**Comment by fabiokounang** [comment]
hello, sorry for the late reply, i turn all of .execute to .query and it never happen anymore. I don't really understand. How does this work ? thank you :D

**Comment by elimelt** [comment]
AFAIK, .query() prepares the statements client-side (in your JS code), whereas .execute() sends the actual query execution plan to MySQL Server as a serialized string.

**Comment by elimelt** [comment]
To add onto this, the reason it fixes your original issue is because your instance of MySQL Server isn't really incurring the overhead of a prepared statement, and thus doesn't count these queries towards the max limit (since the client handles the value substitution). 

Read more on this [here](https://github.com/sidorares/node-mysql2/issues/553)
