### ISSUE TITLE
Typescript typing: Interface 'Connection' without 'query' function

### ISSUE THREAD

**Issue by wsporto** [sidorares/node-mysql2#2120]
I can execute `connection.query(sql)`, but the Typescript `Connection` interface don't have the `query` function.

```ts
import { createConnection } from 'mysql2/promise';

createConnection({
    host: 'localhost',
    database: 'mydb',
    user: 'root',
    password: 'password'
}).then(async conn => {
    const result = await conn.query("select * from mysqluser");
});
```

**Comment by wellwelwel** [comment]
@wsporto, do you have installed the `@types/node` dependency?

**Comment by wsporto** [comment]
@wellwelwel  After installing the `@types/node` dependence it shows the query function. Thanks.

**Comment by sidorares** [comment]
@wellwelwel Any idea how to explain this behaviour? E.g why adding `@types/node` affects types expected in `createConnection().then( here )`?

**Comment by wellwelwel** [comment]
@sidorares, that happens because of the `EventEmitter` from `events`. Every type that extends it will be `any` without the **@types/node** dependency.

To use the **mysql2** and **TypeScript**, it's necessary starting the project like:
```sh
npm i mysql2
npm i -D typescript @types/node
```

---

This weekend I plan to start the **TypeScript** documentation and submit the **PR** using the label `in progress`, so everyone can follow the progress 🙋🏻‍♂️
