### ISSUE TITLE
Release 3.9.4 breaks code that depended on .hasOwnProperty()

### ISSUE THREAD

**Issue by isdampe** [sidorares/node-mysql2#2585]
Pull #2574 looks like it introduced breaking changes that set the `Object` prototype to null (and not `Object.prototype`). A consequence of this is that returned records can no longer call methods of `Object.prototype` such as `hasOwnProperty`.

**Comment by sidorares** [comment]
@wellwelwel maybe freeze Object.prototype instead of inheriting from null?

https://cheatsheetseries.owasp.org/cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.html
https://portswigger.net/web-security/prototype-pollution/preventing

@isdampe the "correct" way of calling `hasOwnProperty` should account for a possible null-prototype https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#objects_created_with_object.createnull but you are right, this should not be introduced in a minor version change

We either need to fix this error somehow in 3.x or bump major version ( and fix in 3.x )

**Comment by wellwelwel** [comment]
@sidorares, I'm reviewing the fundamentals. The security tests didn't pass locally because I tried to do it based on the `prototype` property of an object. For example:

Object:

```js
const test = {};
// test.prototype is undefined;

Object.freeze(test.__proto__); // ✅
```

Class:

```js
const test = class {};
// test.__proto__ is undefined;

Object.freeze(test.prototype); // ✅
```

**Comment by wellwelwel** [comment]
I don't think we'll need a major version bump for this, but I'll perform some tests and check again to be sure.

Related: https://github.com/sidorares/node-mysql2/pull/2574#issuecomment-2047118083

**Comment by wellwelwel** [comment]
@sidorares, we have some problems about [**generate-function**](https://github.com/mafintosh/generate-function) 🔓

---

While trying to solve this issue, I found a vulnerability on [**generate-function**](https://github.com/mafintosh/generate-function) that blocks me to fix it.

Normally, this should work, but it's not possible to do this using `parserFn` due to that vulnerability:

```js
const obj = {};
Object.freeze(obj.__proto__);
```

---

[**generate-function**](https://github.com/mafintosh/generate-function) has ~**1.7 million** dependent public repositories, ~**96** direct public dependencies (npmjs) and over **3 million** downloads per week, so I intend to report it to the creator.

> Last activity on [**generate-function**](https://github.com/mafintosh/generate-function) was 6 years ago and both _PR_ and _Issues_ aren't being answered.

**Comment by wellwelwel** [comment]
Alternatively, it's possible to create a temporary solution until the issue is resolved there.

By using the following helper in `parserFn`, both the **SNYK-JS-MYSQL2-6591084** _(already fixed)_, https://github.com/sidorares/node-mysql2/pull/2574#issuecomment-2047118083 and this issue will be fixed.

> **Reflect and **Proxy** compatibility:** [Node.js 6.4.0](https://node.green/).
> All test suites passed, including new tests based on the errors reported.

```js
const createSafeObject = () => {
  const nativeProps = ['hasOwnProperty', 'toString', 'valueOf'];

  const handler = {
    get(_, prop, receiver) {
      const isNativeProps = nativeProps.includes(prop);

      if (isNativeProps) {
        return (...args) => Object.prototype[prop].apply(receiver, args);
      }

      if (prop === '__proto__') {
        return Object.prototype;
      }

      return Reflect.get(...arguments);
    },
    set(_, prop) {
      const isNativeProps = nativeProps.includes(prop);

      if (isNativeProps || prop === '__proto__') {
        return false;
      }

      return Reflect.set(...arguments);
    },
  };

  const safePrototype = Object.create(Object.prototype);

  return new Proxy(safePrototype, handler);
};
```

---

Then, when that vulnerability is fixed on [generate-function](https://github.com/mafintosh/generate-function), we'll be able to remove it and use it in the right way:

```js
parserFn('const result = {};');
parserFn('Object.freeze(result.__proto__);');
```

---

Please, let me know if you think it's worth using this alternative or if we can wait 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
> _Note to self_
> 
> Including a recommendation from [**MDN**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#objects_created_with_object.createnull) for this in docs (especially in case of a major bump version):
> 
> ```js
> const obj = Object.create(null);
> 
> obj.test = true;
> 
> console.log(Object.hasOwn(obj, 'test'));
> ```
