### ISSUE TITLE
PoolConnection.execute() retrun object v3.9.7

### ISSUE THREAD

**Issue by PeterGamez** [sidorares/node-mysql2#2630]
```js
const [rows] = await PoolConnection.execute(sql)
```
rows are return datatype object
```json
[
  [Object: null prototype] {
    ...
  }
]
```
on 3.9.6 are retrun datatype array

**Comment by sidorares** [comment]
yes, we moved from base `{}` to `Object.create(null)` in 3.9.4 but then had to partially revert that due to #2585 via #2591

Is this breaking something on your side @PeterGamez ?

**Comment by PeterGamez** [comment]
@sidorares yes, how i can fix

**Comment by sidorares** [comment]
Sorry @PeterGamez I still don't understand what issue you are trying to fix

**Comment by PeterGamez** [comment]
@sidorares on `rows` it return datatype object, i want return datatype array

**Comment by wellwelwel** [comment]
> rows are return datatype object

This isn't actually the expected behavior.

For example, we check if the properties are safe and, if so, we create a standard object:

- `execute`

https://github.com/sidorares/node-mysql2/blob/1469228310c4507965a9c674fcdaaa075e185579/lib/parsers/binary_parser.js#L125

- `query`

https://github.com/sidorares/node-mysql2/blob/1469228310c4507965a9c674fcdaaa075e185579/lib/parsers/text_parser.js#L134

---

Could you show an example of how you are returning a null object?
Maybe updating `node_modules` could be a valid check 🙋🏻‍♂️

**Comment by PeterGamez** [comment]
> > ```js
> > [
> >   [Object: null prototype] {
> >     ...
> >   }
> > ]
> > ```
> 
> This isn't actually the expected behavior.
> 
> For example, we check if the properties are safe and, if so, we create a standard object:
> 
> * `execute`
> 
> https://github.com/sidorares/node-mysql2/blob/1469228310c4507965a9c674fcdaaa075e185579/lib/parsers/binary_parser.js#L125
> 
> * `query`
> 
> https://github.com/sidorares/node-mysql2/blob/1469228310c4507965a9c674fcdaaa075e185579/lib/parsers/text_parser.js#L134
> 
> Could you show an example of how you are returning a null object? Maybe updating `node_modules` could be a valid check 🙋🏻‍♂️

update node_modules are work
