### ISSUE TITLE
[bug][regression] mysql2.setMaxParserCache fails with TypeError

### ISSUE THREAD

**Issue by constb** [sidorares/node-mysql2#2752]
Hi!

If I call `setMaxParserCache` imported from mysql2, I get an error:

```
<snip>/node_modules/mysql2/lib/parsers/parser_cache.js:54
  parserCache.max = max;
                  ^
TypeError: Cannot set property max of #<LRUCache> which has only a getter
```

I *really need* to downsize this cache because it always ends up being full and consuming about 300Mb RAM. Probably something about my use case that makes it grow so big…

I believe somewhere along the way `lru-cache` changed its internals and cannot be resized anymore. I'd like if `setMaxParserCache` would throw away an old cache and create a new one with right size in its place…

**Comment by constb** [comment]
> Can you try to find a way to change the size in lru-cache?

According to its readme, they initialize internal structures based on max size and it's too complicated to adjust them to the new size, so it cannot be changed now…

> Alternatively we can refactor parserCache to be part of a single connection

There already is per-connection cache for prepared statements. I doubt there needs to be another one. Also it would reduce cache hit-rate in cases where same queries can be used across multiple connections or even connection pools.

Actually global parser cache makes total sense. As an alternative an option to bypass the cache on specific queries could be implemented, but that maybe a bit too complicated too…

Setting size by recreating cache seems like a simple solution. Instead of `parserCache.max = newMax` just do `parserCache = new LRU({ max: newMax })`

**Comment by constb** [comment]
made a PR to speed up resolution of this one :)

**Comment by wellwelwel** [comment]
I believe it's worth keeping this issue open.

For context:

https://github.com/sidorares/node-mysql2/blob/1abc79965131a9b8bdbe4e8ed00937fa7d999fb7/lib/parsers/parser_cache.js#L6

---

Although it's a very specific case, an example of when we lost 15,000 caches without benefit after `v3.10.1`:

```js
for (let i = 0; i < 15_000; i++) {
  await conn.execute(`SELECT ${i}+${i} as total${i}`);
}

// Allowing 50,000 caches
mysql.setMaxParserCache(50_000);
```

- The expected behavior is to keep all previous cache (15,000), allowing more 135,000.

The same problem reducing cache size:

```js
for (let i = 0; i < 15_000; i++) {
  await conn.execute(`SELECT ${i}+${i} as total${i}`);
}

// Allowing 10,000 caches
mysql.setMaxParserCache(10_000);
```

- The expected behavior is to keep 10,000 previous cache (from most recently used), removing 5,000 if exist.

When `setMaxParserCache` is used before a cache is generated, there is no loss.

---

> [!NOTE]
>
> I opened a _PR_ (#2988) proposing a library change, where we could basically do this internally:
>
> ```ts
> parserCache.resize(max);
> ```
