### ISSUE TITLE
Prepared statements and parameters.

### ISSUE THREAD

**Issue by TheMarlboroMan** [sidorares/node-mysql2#290]
Hi:

We just noticed that, given a procedure "do_something" that is supposed to get 5 input parameters you can do all kinds of funky things. First off, a regular usage:

let qstr="CALL do_something(?,?,?,?,?)";
let params=[1,2,3,4,5];
connection.query(qstr, params, function(err, res) {...});

Something weird...

let qstr="CALL do_something(?,?,?)";
let params=[1,[2,3],[4,5]];
connection.query(qstr, params, function(err, res) {...});

Something weirder...

let qstr="CALL do_something(?,?)";
let params=[1,[[2,3],[4,5]]];
connection.query(qstr, params, function(err, res) {...});

Is this intentional behaviour?.

**Comment by sidorares** [comment]
hi @TheMarlboroMan

Currently "execute" command just sends each input parameter as string, see https://github.com/sidorares/node-mysql2/blob/cd16a0a7ad2d273fa5126135479d4698bd554cea/lib/packets/execute.js#L32-L49

and https://github.com/sidorares/node-mysql2/blob/cd16a0a7ad2d273fa5126135479d4698bd554cea/lib/packets/execute.js#L84-L97

More specifically, the logic is as follows:
1) if it's date, format as mysql date string
2) if it's a Buffer, use bytes as is
3) if string, convert to utf8 byte sequence
4) if null, don't send ( but set a bit in the null bitmap )
5) otherwise send paremeter.toString()

I think the count must match one returned from "prepare" but currently there is no check, execute just packs as many parameters as you pass. I think server just ignores extra parameters

**Comment by TheMarlboroMan** [comment]
Sorry it took so long to reply: I had forgotten about github alltogether.

Thanks a lot for the information. I am pretty much sure the prepare ignores the check but we'll double check on our side to make sure everything is ok and in place, just in case it gets changed in the future.

Thanks!.
