### ISSUE TITLE
npm run benchmark doesn't work

### ISSUE THREAD

**Issue by sushantdhiman** [sidorares/node-mysql2#368]
**Error**
```bash
in /var/www/node-mysql2 on git:master ✖︎ [17:53:22]
→ npm run benchmark

> mysql2@1.0.0-rc.10 benchmark /var/www/node-mysql2
> ./benchmarks/run-unit.js

0 0 0
undefined [=---------------------------------] /var/www/node-mysql2/benchmarks/run-unit.js:86
      m(function() {
      ^

TypeError: m is not a function
    at Immediate._onImmediate (/var/www/node-mysql2/benchmarks/run-unit.js:86:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Reason ?**
[benchmarks/unit/packet_parser.js](https://github.com/sidorares/node-mysql2/blob/master/benchmarks/unit/packet_parser.js) doesn't export a `function`, it doesn't export anything actually.

**Comment by sidorares** [comment]
thanks, I'll fix this.

I'm actually working on a new version of benchmark right now ( similar to https://gist.github.com/sidorares/ffe9ee9c423f763e3b6b , but using EC2 instances and wrk2 instead of wrk )

**Comment by sidorares** [comment]
I ended up returning empty function from that module, need to revisit it at some time later. The goal is to perf test packet parser which de-frames mysql packets from stream of chunks of network packets. Hot path is network packet = exactly one or more full packets ( this happens when response fits in one frame, usually 65536 bytes ), but we need to be able to handle any size ( even 1 byte might left if for example payload is 2 packets which total to 65537 bytes => two network packets 65536 + 1 byte)
