### ISSUE TITLE
Feature request: pooling with custom streams

### ISSUE THREAD

**Issue by mscdex** [sidorares/node-mysql2#408]
Right now `mysql2` supports passing a custom stream to use as the underlying server connection, which is great. However it would be nice to have some easy way to implement similar support for pooling.

Maybe it's as easy as the user providing some function that is passed a callback that gets called with a stream to use for the new connection. I am not familiar with the existing pooling mechanism, so it may be a bit more complicated than that?

Example:

```js
var pool = mysql2.createPool({
  // ...
  createConnection: function(callback) {
    // ...
    if (err) return callback(err);
    callback(null, stream);
  }
});
```

**Comment by sidorares** [comment]
That definitely used to work before. Api is the same as with non-pool connections, but you must provide "factory" instead of just stream as new connection would need new stream (similar to your example). 

https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#connecting-using-custom-stream

```js
var mysql = require('mysql2');
var pool = mysql.createPool({
  database: 'test',
  user: 'foo',
  password: 'bar',
  stream: function (cb) {
      // get a read/write stream from somewhere.
      cb(null, newStream);
  }
});
```

please comment if this broken, I'm not sure custom streams are covered with tests atm

**Comment by mscdex** [comment]
Ah ok, I must have overlooked that. Thanks for the quick reply.
