### ISSUE TITLE
Chinese column names become garbled in mysql2^1.0.0

### ISSUE THREAD

**Issue by NijiharaTsubasa** [sidorares/node-mysql2#422]
We have some pretty old tables with some Chinese column names like this:
````sql
CREATE TABLE `商城` (
 `商品类型` varchar(255) NOT NULL,
 `商品说明` varchar(255) NOT NULL,
 `价格` int(11) NOT NULL,
 `剩余` int(11) NOT NULL,
 PRIMARY KEY (`商品类型`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
````

We used to be using **mysql2 1.0.0-rc.11** and everything is OK:
![qq 20161003224851](https://cloud.githubusercontent.com/assets/7794838/19042223/c7a6f328-89bd-11e6-8328-6cdc7775db33.png)

Today I was migrating the app to another server and npm install'd **version 1.1.0** and everything is broken:
![qq 20161003225318](https://cloud.githubusercontent.com/assets/7794838/19042226/c8a05fbc-89bd-11e6-9ebd-93c4bd9487d5.png)

I also tested version 1.0.0 and no luck, the column names are still garbled, and I have to roll back to 1.0.0-rc.11

Some details:
Only varchar columns was good, name of other columns (like the int ones) all become garbled.
The charset of my database, table and varchar columns are all utf8.
The js file being executed is also utf8.
The charset of the connection is also utf8. ("set names utf8")

**Comment by sushantdhiman** [comment]
Can you try without `set names utf8` ?

**Comment by NijiharaTsubasa** [comment]
@sushantdhiman No luck, everything is the same with or without `set names utf8`

**Comment by sushantdhiman** [comment]
@NijiharaTsubasa It seems issue might be on https://github.com/sidorares/node-mysql2/blob/b3c319469c929e6c0c1fee59d600e67d9c4b0360/lib/packets/column_definition.js#L54 , may be we aren't passing right encoding.

Can you please add a PR with failing test case?

**Comment by sidorares** [comment]
@NijiharaTsubasa can you post what's returned in the fields array (third argument in callback - `conn.query(sql, function(err, rows, fields) {...})`?

What happens when you do `set names utf8mb4`?

Which tools you used to create table? Was it created with node client as well?

utf8 in mysql is complicated: when encoding is set as 'utf8' the [cesu-8](https://en.wikipedia.org/wiki/CESU-8) is used in fact. If `utf8mb4` charset is used, data is encoded with 'regular' utf8, but all chars in metadata (field names etc) outside of BMP replaced with '?' symbol.

I think what currently happens is:
1) when originally created, table names saved as utf8 (not cesu-8). Mysql stored tham as is, but it's not aware that it's utf8
2) if you use mysql2 1.0.0-rc.11 data is treated again as utf8 (which sometimes look like it is working, but in some other cases on the server it'll be broken: counting chars, sorting etc - mysql assumes encoding is cesu-8 and in fact we saved utf8)
3) if you use node-mysql2 1.1.0 it sees charset "utf8" and uses cesu-8 codec do decode strings.

Potential solution:
1) re-create empty table using node-mysql2 1.1.0.
2) on mysql server, select old table into newly created
3) drop old, rename new to old

**Comment by sidorares** [comment]
@NijiharaTsubasa see very lengthy discussion on #374 pr

**Comment by sidorares** [comment]
actually all chars from table names have 3 bytes when encoded using utf8, so my assubmptions might be incorrect

```
> var a = Buffer.from('商品类型')
undefined
> a.length
12
> var a = Buffer.from('商品说明')
undefined
> a.length
12
> var a = Buffer.from('价格')
undefined
> a.length
6
> var a = Buffer.from('剩余')
undefined
> a.length
6
```

**Comment by NijiharaTsubasa** [comment]
@sidorares 
Sorry I can't use my computer until October 7th so can't do some tests now but I can say that fields argument is also garbled.
Tables were all created using phpmyadmin **via a sql file directly imported**. I will test create with mysql2 but I don't think it will work.

Maybe I will consider use utf8mb4 instead ~~but some users of my program have a rather old mysql that don't support utf8mb4 maybe I'llask him update his first~~

**Comment by sidorares** [comment]
@NijiharaTsubasa when you back to your computer, can you provide a log output from `` select * from `商城` limit 1 `` when mysql2 client is created using `debug: true` option? (provided you don't have sensitive data there).

**Comment by sidorares** [comment]
@NijiharaTsubasa fix is in master and will be in npm soon, let us know if it works for you
