### ISSUE TITLE
Is args optional in promisePool.execute(sql, args)?

### ISSUE THREAD

**Issue by yura-chaikovsky** [sidorares/node-mysql2#485]
Implementation of `Pool.prototype.execute(sql, values, cb)`:
https://github.com/sidorares/node-mysql2/blob/master/lib/pool.js#L150
expects `cb` always be a function. But `promisePool.execute(sql, args)`:
https://github.com/sidorares/node-mysql2/blob/master/promise.js#L102
sends `doneCb` only if `args` has truthy value. 

It looks like a bug. Expecting either `args` has a default value `[]`, or throw an error for missing argument.

**Comment by sushantdhiman** [comment]
I don;t think `args` should be optional in a real world `execute` command, because you always want to bind some parameter, otherwise why bother using it in the first place (you can just use query).

I think code is copy paste from `PromisePool.Query`. But it can be optional, just `values` passed to `execute` will be `undefined` (query without no bind)

But i see an issue here, if someone pass `args` undefined, connection will never be released on this line https://github.com/sidorares/node-mysql2/blob/master/lib/pool.js#L159, because execute will only call 2nd argument and ignore the 3rd (release cb) (https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L584)

I think we should do some changes

- rename `args` to `values` in `PromisePool.Execute` context, which will reduce some confusion
- remove optional `args` if condition altogether
- Force or warn user if `values` are undefined ?

**Comment by danieljuhl** [comment]
@sushantdhiman isn't prepared statement ONLY used for `.execute()` and not for `.query()`? In that case, I do see use cases, where you'd use a prepared statement for an often used query, even without additional `args`.

**Comment by sushantdhiman** [comment]
@danieljuhl what is the advantage of unbounded prepared query over normal query ? DB cache will treat both in same way as there is no changing parameters in both.

But as I said above, its possible to build a prepared query without any param, but doing that will lead to a  unreleased connection. We have to fix that. Then user can decide if they need to bind params or not.

**Comment by sidorares** [comment]
> what is the advantage of unbounded prepared query over normal query

sql text not sent over network each time. Other than that performance should be similar, sql parsing/optimisation is cached in modern sql versions

> We have to fix that.

yes :) I'll try to look tomorrow

**Comment by danieljuhl** [comment]
@sushantdhiman @sidorares I know, that handling in SQL is the same, but yes, as said, sql text is not sent over network each time. So my comment, was just to point in a direction, where it would actually be used, without values/args.
