### ISSUE TITLE
execute.js not testing for undefined

### ISSUE THREAD

**Issue by GotJimmy** [sidorares/node-mysql2#493]
I ran into a problem passing an undefined value to a query which caused the node server to crash. The problem was found in execute.js for all 3 occurrences of
`this.parameters[i] !== null` 
Changing these 3 occurrences to
`this.parameters[i] !== undefined`
eliminated the problem. Checking for null and undefined would probably be ideal.

**Comment by sidorares** [comment]
How do you think `undefined` should be handled? Javascript `null` is mapped to mysql `NULL` type, but there is no "undefined" type in mysql. I feel like the best behaviour should be to return error early (with message like 'Parameter cannot be undefined, did you want to use NULL value?')

At the moment all non-null (and non-Buffer) values a serialised as string result of `value.toString()` (which obviously crashes for `undefined`)

**Comment by JimmyGot** [comment]
I didn't want to send null nor undefined -- it just happened because I JSON decode an url-encoded request body. That's how the undefined value got executed and caused the crash on line 47 of execute.js because of .toString() from an undefined parameter.
`var str = this.parameters[i].toString();`
However, I changed line 35   `if (this.parameters[i] !== null) {`
to  `      if (this.parameters[i] !== undefined) {`
and therefore never got to line 47. I also had to change lines 67 and 89 and no error occurred anymore.

**Comment by sidorares** [comment]
so I guess in your case early error would work best

**Comment by JimmyGot** [comment]
Well, in this case it would avoid the error. Of course, I'll add additional checking of my parameters before sending them to execute. But if sending an undefined parameter happened to me it may also happen to someone else by accident.

**Comment by dougwilson** [comment]
@sidorares FWIW, `sqlstring` treats both `undefined` and `null` as SQL `NULL`, and I do agree that at least the way in which the packet execute is throwing is hard to understand. Perhaps either `this.parameters[i] !== null` -> `this.parameters[i] != null` to behave similar to `sqlstring` or at least `this.parameters[i].toString()` -> `String(this.parameters[i])` which will call `.toString()` if it exists, otherwise `Object.prototype.toString`.

**Comment by sidorares** [comment]
I think I'll do `String(this.parameters[i])` and "error if this.parameters[i] is undefined" together. I don't think that sending `'undefined'` as string if you misspelled key name is good behaviour

**Comment by sushantdhiman** [comment]
I agree with @sidorares , throwing early error will be better in this case. Otherwise someone can missspell something or data is undefined, and we will end up silently inserting `null`. If they want to set data to `null`, let them explicitly supply it as `null` and throw for `undefined` values

**Comment by sushantdhiman** [comment]
Also fixing this issue will close https://github.com/sidorares/node-mysql2/pull/480 (PR)

**Comment by theFroh** [comment]
Got bit by this, hell of a stacktrace to dig through if you accidentally pass undefined in!

**Comment by Gregoor** [comment]
Hi @sidorares,
thanks for the great lib. I'm running into this problem as well. Wouldn't #689 solve that?

**Comment by gazoakley** [comment]
There's now a checked for undefined bind params:

https://github.com/sidorares/node-mysql2/pull/718
