### ISSUE TITLE
when a long sql is executed, it seems be truncated

### ISSUE THREAD

**Issue by eblics** [sidorares/node-mysql2#500]
![image](https://cloud.githubusercontent.com/assets/7858041/22283801/15615ed6-e31f-11e6-917a-0be7e2cad3f6.png)

you can see this picture. In fact, the sql can be executed in sql browser.

**Comment by sidorares** [comment]
can you give more details? Full sql, connection options, if `connection.query()` (text protocol ) used or `connection.execute()` ( binary protocol / prepared statements )

**Comment by dougwilson** [comment]
That error string came directly from the MySQL server, which does truncate the SQL in the error message (mainly because it's internal buffer is only so large). The issue it is showing you is that you are sending a query with multiple statements but do not have multi statements enabled in this library, which is why it is throwing a SQL syntax error on the `;` semicolon character.
