### ISSUE TITLE
Error thrown with correct SQL query: "Column count doesn't match value count at row 1"

### ISSUE THREAD

**Issue by nishaad78** [sidorares/node-mysql2#679]
Using this function call throws an error: 
```
connection.execute('INSERT INTO `options` (`tag`, `category`, `image_uri`, `icon_uri`) VALUES (?) ON DUPLICATE KEY UPDATE `category`=?, `image_uri`=?, `icon_uri`=?;', 
	[
		['VAN', 'VEHICLE', 'van.png', 'van_ico.png'],
		'VEHICLE', 
		'van.png', 
		'van_ico.png'
	]
)
```

Error thrown: `message: 'Column count doesn't match value count at row 1', code: 'ER_WRONG_VALUE_COUNT_ON_ROW', errno: 1136` 

Using Promise Wrapper on node v8.9.1

Same function call works with connection.query with node mysqljs/mysql lib

**Comment by sidorares** [comment]
this is expected behaviour, `.execute()` and `.query()` behave differently. You should get same results using mysql2 + `.query()`.

With `.query()` placeholders are substituted in client side, and resulting sql string is sent to server.
With `.execute()` query with placeholders is sent to server ( on first execution ) and then only list of parameters sent to server. `.query()` does very limited parsing of the string and `.execute()` performs full sql compilation. See documentation on what's allowed in prepared statements and restriction for placeholders here - https://dev.mysql.com/doc/refman/5.7/en/sql-syntax-prepared-statements.html
