### ISSUE TITLE
How macke "const dbs = await mysql.createConnection" as global?

### ISSUE THREAD

**Issue by sigmallc** [sidorares/node-mysql2#750]
There is a code app.js:

```js
import Koa from 'koa'
import mysql from 'mysql2/promise'

const dbs = await mysql.createConnection({host: '*',user: '*',password: '*',database: '*'});

const ping = async () => {
    try{
        let [rows] = await dbs.execute("SELECT 'OK' as ok");
        console.log("MySQL connect",rows[0].ok )
    }catch(e){
        console.error("MySQL connect FAILED",e)
        process.exit(-1)
    }
};

ping()


app.use(async (ctx, next) => {
    ctx.getDB = () => {
        return dbs
    };
    await next()
});
```

The problem is that it gives an error on "await". The problem with "await" is solved if you transfer ..dbs = await mysql.createConnection .. inside each function. But for me it does not fit. How to make "dbs" visible in all functions while dealing with the Promise.

**Comment by sidorares** [comment]
preferred way is to use connection pool

Is your problem mainly because node does not allow top level await? I think this is going to be added in node 10. Also you can use something like https://github.com/robertklep/top-level-await right now.

You can also await single Promise multiple times so easy fix in your code is to store reference to promise 

```js
   const connPromise =  mysql.createConnection();

   // later use it
   const conn = await conPromise;
   await conn.execute(/* ... */);
```

**Comment by sigmallc** [comment]
Thank you. It works. Please add this case to the documentation. I'm new, tell me plz how to work with the pools and the principle of their work. I will be grateful for the correct reference.
