### ISSUE TITLE
Synchronous result stream processing

### ISSUE THREAD

**Issue by dendrochronology** [sidorares/node-mysql2#770]
I'm having trouble finding clear examples of how to perform a query and process the result stream synchronously. I've tried the following example from [this comment](https://github.com/sidorares/node-mysql2/issues/677#issuecomment-345491461) but the`Promise` hangs, so the script never executes the next line, and node just sits there without exiting (never reaches the connection close line either):

```javascript
const thingsWeCareAbout = new Map();

await new Promise((resolve, reject) => {
  const s1 = connection.query('SELECT a lot of stuff').stream();
  s1.on('result', row => {
    // logic to determine if we care about this row
    thingsWeCareAbout.set('foreignKeyFromQuery', ['stuff', 'to', 'process', 'later']);
  });
  s1.on('end', resolve);
  s1.on('error', reject);
});

doMoreStuff(thingsWeCareAbout); // this never executes; script is hung
```

I need to pull millions of rows, but don't want to load the whole thing into memory. I also can't move on to the next step until all the rows have been examined by a function that determines if we need to do something in the next step (it's a chain of ETL functions for a data warehouse).

**Comment by dendrochronology** [comment]
A colleague suggested removing `.stream()` from the query, and it works! Did I miss that in the docs somewhere?

**Comment by sidorares** [comment]
Because you are not composing streams there is no point in using `.stream()`

I think what happens is no one reads from other side of the stream and it pauses itself ( backpressure handling ) - https://github.com/sidorares/node-mysql2/blob/80c55ef2b60572ef7b0ac7bee2eb45db8de6a516/lib/commands/query.js#L258

In order to just read rows without buffering them in memory `.query()` with no callback and 'result' events handler is enough
