### ISSUE TITLE
Auto "unpreraring" statements 

### ISSUE THREAD

**Issue by blablapolicja** [sidorares/node-mysql2#773]
I'm using `execute()` for prepared statements 

Are my statements automatically unprepared (closed) after reconnection?

Example:

1. I call `execute()` with my statement
2. My connection fails
3. I create new connection
4. I call `execute()` again with the same statement

Is my statement prepared again? Or I have to unprepare (close) it manually and prepare again?

Thank you

**Comment by sidorares** [comment]
> Are my statements automatically unprepared (closed) after reconnection?

Yes, but not by the driver, it's how mysql server behaves.
If you look at statement id it's always sequential integer starting with 1 for every new connection. Statements are not shared between connections on the server ( two separate connections can both have statement with id `1` mapped to different queries )

> Is my statement prepared again
Again, no. New connection is always "fresh" from prepared statements point of view

**Comment by blablapolicja** [comment]
Thank you for the quick reply

Is it better to use manual prepare in terms of performance? I need to gain maximum insert-per-second performance

**Comment by sidorares** [comment]
Won't make much difference. Usually when you insert lots of rows bottlenecks are 1) network latency and 2) server write performance

MySQL protocol is half duplex, you send command, wait for response from server and only after that send another command. There are ways to work around this, I suggest to benchmark all of them: Insert "mini-batches" - build insert queries that contain multiple rows & repeat; use stored procedure, send data that is compressed in some way, unpack on server; use 'load data infile' (probably with local stream of data instead of real fs file)

**Comment by sidorares** [comment]
And of course make sure you don't create connection on each insert. Also using multiple connections via pool can help with latency (but make sure server can handle that, too much parallel load could actually slow it. Each new connection is usually new execution thread on server with all associated overhead - context switches, stack memory etc )

**Comment by blablapolicja** [comment]
Thank you for "extended" reply)

> There are ways to work around this...

The only way that I'm using (and the only way I actually CAN use) is multiple rows inserts. Data is inserted by 10 rows per query every 1-10 ms. So, one of the main goals for me - is to improve the insert speed on the level of connection to MySQL server

> And of course make sure you don't create connection on each insert

I'm using one connection for all inserts. And I don't think, that pooling can be useful for me
