### ISSUE TITLE
Inserting UTC dates

### ISSUE THREAD

**Issue by hluedeke** [sidorares/node-mysql2#774]
I'm not sure where to put this because I'm honestly not sure if it's a bug or not. 

I'm currently using node-mysql2 v1.5.3 with node v6.11.0.

When I went to insert a UTC Date into mysql using this library with `Date()` objects as query variables, the library would mutate the date. Here's some (untested) code to demonstrate what I mean:

```JavaScript
const date = new Date().getTime(); // Simulating passing in a UTC float to my function
console.log(date); // Will output, say '2018-04-18T00:00:00Z'
const query = 'INSERT INTO Table (id, date_column) VALUES (?, ?);';
const q = db.query(query, [id, new Date(date)], (err, results) => {
  console.log(q.sql); 
  // Outputs 'INSERT INTO Table (id, date_column) VALUES (5, '2018-04-17T19:00:00');'
});
```

I am using the suggested `typeCast` solution in the docs for converting output to UTC, but I guess I still wasn't expecting a 'hidden' conversion on input.

That being said, how I got around this problem was inputting ISO strings instead of Dates as input:

```JavaScript
...
const date = new Date(utcFloat);
const q = db.query(query, [id, date.toISOString()], (err, results) => {
...
```

I'm not sure if this is currently being fixed with the new timezone support PR's I see currently being worked on, but I guess I wanted to leave this here in case someone else was having problems with inserting UTC timestamps and to bring it to attention in case it does in fact need to be addressed.

**Comment by sidorares** [comment]
The reason for conversion is because mysql date/time does not store timezone internally, and best driver can do is to just drop it from the input. My suggestion is if you can, avoid using time types in mysql altogether and use integer timestamps. 

Both mysql2 and mysql modules use this code to serialize Dates: https://github.com/mysqljs/sqlstring/blob/8f193cae10a2208010102fd50f0b61e869e14dcb/lib/SqlString.js#L119-L164 ( when no prepared statements used, in case of PS dates are sent in binary form but again, without timezone )

Timezone seem to be passed here - https://github.com/sidorares/node-mysql2/blob/1f75838e62ac7e7d13a060f420f3b9359cf3aaf5/lib/connection.js#L553 
Can you check it's actually set to correct value and the value passed from your code down to `sqlstring.format()` call?

**Comment by hluedeke** [comment]
I did not have timezone setup in my config file. I actually used to and then took it out after converting form node-mysql to node-mysql2, particularly after reading all the information on having to use the typeCast function to retrieve UTC dates. I guess I just assumed (incorrectly) that one was a replacement for the other.

I'll add it back in and see if that fixes it.

Thanks!

**Comment by hluedeke** [comment]
Just tested it, and it does work. Thank you!
