### ISSUE TITLE
Escape string with mysql like doesnt work properly

### ISSUE THREAD

**Issue by checkthestatistics** [sidorares/node-mysql2#793]
Im trying to use this sql statement with mysql LIKE operator, however it doesn't work properly, since it doesn't return anything.
`SELECT * FROM products p WHERE p.name LIKE '%?%'`
`const [ getProducts ] = await res.db.execute(sql, [productName]);`
It only works if product name in sql is hard coded like:
`SELECT * FROM products p WHERE p.name LIKE '%${productName}%'`

**Comment by sidorares** [comment]
@checkthestatistics  change it to this:

```js
const sql = `SELECT * FROM products p WHERE p.name LIKE ?`;
const [ getProducts ] = await res.db.execute(sql, [`%${productName}%`]);
```

I should probably make execute check parameters more strictly and throw error when passed number of parameters is more than expected ( in your case compiled prepared statement had zero parameters because server treated `'%?%'` as string literal and not as parameter placeholder
