### ISSUE TITLE
pool.end() throws Cannot read property 'once' of undefined

### ISSUE THREAD

**Issue by RedSpid3r** [sidorares/node-mysql2#829]
calling `pool.end()` in my script throws:

```
TypeError: Cannot read property 'once' of undefined
at /home/********/node_modules/mysql2/lib/pool.js:158:25
at /home/********/node_modules/mysql2/lib/pool.js:36:14
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)```

**Comment by RedSpid3r** [comment]
managed to resolve!

**Comment by JeremieDemarchez** [comment]
Hello,
I'm facing the same issue.
How did you solve it ?
Thanks !

**Comment by sidorares** [comment]
@RedSpid3r what was the root cause in your case?

@JeremieDemarchez I need more info to be able to help - stack trace, code sample etc

**Comment by StephenFluin** [comment]
I'm hitting this right now. Seems like one of my queries isn't fully resolving is my guess?

Error:

```
TypeError: Cannot read property 'once' of undefined
    at /super/workspace/stephenfluin/watcher/node_modules/mysql2/lib/pool.js:147:27
    at /super/workspace/stephenfluin/watcher/node_modules/mysql2/lib/pool.js:44:37
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

I can't share the full code, but I've tried a few things unsuccessfully. This is how I'm ending the pool:

```
await this.db.query(SQL`DELETE FROM queue WHERE id = ${result.id}`);
await this.db.removeAllListeners();
await .db.end().then(() => console.log('db should be closed'));
```

All of my code (including the final console log) is running well, but then I get the error a few ms later.

**Comment by StephenFluin** [comment]
I figured it out. My problem was that I had a query **WAY EARLIER** in my code that was missing an await.

**Comment by stimularity** [comment]
Wow you people are terrible. Post the solution if you solve the problem to help other people.

I was running into the same error:
`Cannot read properties of undefined (reading 'once')`

The issue was because I was calling `database.end()` before all running queries were complete.
I had a promise chain of queries with one "misc" query being run to update something on the side.

Solution, put a timeout around the end call or correctly chain all promises or use Promise.all() before calling .end()
