### ISSUE TITLE
connection.execute does not work with arrays (IN statements)

### ISSUE THREAD

**Issue by FunnyB0y** [sidorares/node-mysql2#913]
So for whatever reason, the following code does not work (it doesn't actually delete the row, even though the statement is correct.)
```
let query =
    `
        DELETE FROM
            items
        WHERE
            mongodb_id IN (?);
    `

let fields =
    [
        args._ids
    ]
await connection.execute(
    query,
    fields
)
```

But when I run this, it works (same query and fields).

```
let formatted =
    mysql.format(query, fields)
let results =
    await
    connection.query(
        formatted
    )
```

Any reason for the result difference?

**Comment by vlasky** [comment]
The reason why connection.execute() isn't working for you is because the query needs to have a separate question mark placeholder corresponding to each element in the array.

Here is an example of code that will dynamically create the correct number of comma-separated question mark placeholders equal to the number of elements in the array fields.

```
let fields [0,1,2,3,4,5,6]
let query = `DELETE FROM items WHERE mongodb_id IN (${Array(fields.length).fill("?")})`;
//query will be set to "DELETE FROM items WHERE mongodb_id IN (?,?,?,?,?,?,?)"
let results = await connection.execute(query, fields);
```

The reason why your current syntax works when using connection.query() is because the query and the fields are concatenated into one string before being passed to MySQL.

In contrast, connection.execute() results in a prepared statement handle being created and MySQL needs to precisely know how many parameter values will be passed it to the handle each time that it is called.

**Comment by FunnyB0y** [comment]
@vlasky `args._ids` is an array, so there's an array of arrays i.e. [ [1,2,3,4] ]. What happens if I need to use the array and then something else? e.g.

```
let query =
    `
        DELETE FROM
            items
        WHERE
            mongodb_id IN (?)
            AND
            account_id = ?;
    `
```

**Comment by vlasky** [comment]
@FunnyB0y you have to concatenate the arrays together. The corresponding parameter value elements in the array are resolved sequentially, question mark by question mark. Here's an example:

```
let mongdb_ids = [0,1,2,3,4,5,6];
let account_id = 777;
let query = `DELETE FROM items WHERE mongodb_id IN (${Array(fields.length).fill("?")}) AND account_id = ?`;
//query will be set to "DELETE FROM items WHERE mongodb_id IN (?,?,?,?,?,?,?) AND account_id = ?"
let results = await connection.execute(query, [].concat(mongodb_ids, account_id);
```

**Comment by sidorares** [comment]
If you need to build sql dynamically there is no much point in prepared statements, prob better to use `.query()`

**Comment by FunnyB0y** [comment]
@sidorares My bad, I thought it was internalling calling `.format` and `.query`

**Comment by sidorares** [comment]
> My bad, I thought it was internally calling .format and .query

no, `.execute()` and `.query()` are very different, they just happen to have similar api
