### ISSUE TITLE
Question about `mysql` vs `mysql2`

### ISSUE THREAD

**Issue by jsumners** [sidorares/node-mysql2#921]
Two years ago a note was added to the readme that talks about migrating code to the `mysql` module:

https://github.com/sidorares/node-mysql2/blame/abe9624e5571c7cdfcef5e633f7a9cf1011de0d1/README.md#L29

I'm a little confused. Does this mean the `mysql2` module is intending to cease development and become one with the `mysql` module? If so, what is the status of that?

I am trying to determine which module to rely upon as both have some significant outstanding issues and PRs which make it difficult to gauge the liveliness of each module.

**Comment by sidorares** [comment]
Hi James!

There is no plan to "hey let's just have just one mysql module moving forward", but at the same time we would like to reduce code duplication and share it between mysql and mysql2 via small modules. Right now the only big shared piece is `sqlstring` package which is responsible for client side parameter interpolation. If you like to help with this process you definitely welcome, possible directions could be: constants, config parameters handling / validation, and maybe e2e tests as we aim for api compatibility

> I am trying to determine which module to rely upon as both have some significant outstanding issues and PRs which make it difficult to gauge the liveliness of each module.

My rule for choosing modules is if there is an issue I'm not prepared to solve _myself_ I'm not using it.
mysqljs/mysql "support" is slightly better. Both modules have pretty much one active maintainer ( and few more people to help occasionally ) but Doug Wilson ( mysqljs/mysql maintainer ) is usually much quicker to respond and produce quality code. I'm often too busy with day job and 6 kids and some PRs and issues remain open for weeks ( I tend to batch them, not often have chunks of continuous uninterrupted time )

Note that both Dough and myself not get paid for this work. If you really want some issues to be solved quicker there might be a possibility to approach us and offer money in exchange for some dedicated time ( this is probably true for most other open source code ).

**Comment by sidorares** [comment]
Some other difference ( I might be wrong, it's just a general feeling ):

mysqljs/mysql is production quality and in maintenance mode. We are happy to merge new code if it's already production quality ( unit tests, backwards compatibility, documentation etc ) Some PRs are open because nobody wanted to finish work up to these standards. Usually new code functionality is coming from users, there is no active development from maintainers

mysql2: I'm slightly less picky when accepting PRs and also write new code myself and have long queue of features I'd like to add, so it's a bit more "experimental" and might get some features first. Having said that, it's also actively used in production and might be a good fit for you. Good thing is that often you can just swap mysql and mysql2 if you unhappy with either

**Comment by jsumners** [comment]
I wasn't making a statement on the availability of people to solve the issues. Simply trying to make a decision based on the available evidence and my own time.

Thank you for the responses. They are helpful.

**Comment by sidorares** [comment]
No problems @jsumners !
