### ISSUE TITLE
Using transaction without getConnection() on connection pool

### ISSUE THREAD

**Issue by sharmaar12** [sidorares/node-mysql2#925]
I am trying to implement transaction with mysql promise. I know correct way to implement is:
```
  const conn = await pool.getConnection();
  await conn.beginTransaction();
  await conn.query('INSERT INTO ...', params);
  await conn.commit();
  conn.release();
```

I want to know why we have to call getConnection() function to use transaction?
If I am correct we have to execute "BEGIN ,INSERT..., COMMIT" queries on same connection instance and if we don't use getConnection() there is probability that they may get executed on different connection instances. But if that is the case why the following inserts nothing in the DB (**_If we execute it once_**).

(_I have deliberately skipped the explicit COMMIT, please read last question_)
```
router.post('/tran1', async (req, res) => {
    await pool.query('BEGIN');
    await pool.execute('INSERT INTO temp_test (col1, col2) VALUES (?, ?);',['2','tran1']);
    res.send('Completed');
});
```
In my opinion, the BEGIN and INSERT INTO should have executed on different connection instance hence INSERT should not have context of transaction it should get committed.

Now, if you say, I have not added COMMIT there then why, if we call above route n times, it adds (n-1)  rows in DB so I think the transaction context is getting preserved somehow.

I have referred to this https://github.com/sidorares/node-mysql2/issues/808#issuecomment-405212527 but I want to know why getConnection() is needed?

**Comment by aikar** [comment]
I am not sure if you are asking a question or filing a bug...

Yes, there is a bug. I was literally coming here to file an issue about this context.

The issue lies that when a connection is returned to the pool, the state is not reset.

node-mysql2 simply needs to resend the CHANGE USER packet to the user the connection was opened with, and this will reset state.
This is common behavior for connection pools to do in any programming language.

In your case, you MUST use .getconnection() because the pool needs to know when you are done using a single reference to the connection.

As you said, in your flawed code, both queries can operate on different connections, or they might end up on the same one, nothing is guaranteed.

the released connection is appended to the end, so when you have more than 1 connection open, both of those queries will end up on different connections.

@sidorares would you rather I file this as a separate issue or leave here?

**Comment by sharmaar12** [comment]
@aikar I was just asking a question about why the .getConnection() is needed. You answered that already.
